#! /usr/bin/env sh

. "$HOME/.cache/wal/colors.sh"
dmenu_cmd="dmenu -p theme:  -nb $color0 -nf $color7 -sb $color9 -sf $color15"
sxiv_cmd="sxiv" # should support the same options as sxiv; specifically: bortN
theme_dir="$HOME/.local/share/wal-themes"
name="$(basename "$0")"
usage_message="Usage:
        $name                   choose a theme using dmenu and apply it
        $name h/-h/--help       print this help and exit

        $name a THEME           apply THEME
        $name d THEME           delete THEME
        $name e THEME           open THEME's colours.json in \$EDITOR ($EDITOR)
        $name i THEME           print info on current wallpaper if such exists
        $name l                 list valid theme names
	$name l-icewm-menu      format list of themes for an icewm menu entry
        $name n THEME           create 'THEME' from current pywal cache
	$name p THEME           edit a theme's post-application script
        $name r                 apply random theme
        $name s                 select theme graphically and apply it
        $name u THEME           write current pywal configuration to 'THEME'
        $name install THEME*    install all supplied THEMEs"

icon_size="16" # for theme icon generation, e.g. for icewm menus
isxis="${icon_size}x${icon_size}"
xresources="$XDG_CONFIG_HOME/X11/Xresources"
conf_dir="${XDG_CONFIG_HOME-"$HOME/.config"}"
wal_conf_dir="${conf_dir}/wal"
wal_cache_dir="${XDG_CACHE_HOME-"$HOME/.cache"}/wal"

# wal doesn't expose decimal component values and sh doesn't
# have floating-point arithmetic out of the box
[ -e "${wal_conf_dir}/templates/colors-decimal" ] || \
	echo "{background.red}, {background.green}, {background.blue}
{foreground.red}, {foreground.green}, {foreground.blue}
{cursor.red}, {cursor.green}, {cursor.blue}
{color0.red}, {color0.green}, {color0.blue}
{color1.red}, {color1.green}, {color1.blue}
{color2.red}, {color2.green}, {color2.blue}
{color3.red}, {color3.green}, {color3.blue}
{color4.red}, {color4.green}, {color4.blue}
{color5.red}, {color5.green}, {color5.blue}
{color6.red}, {color6.green}, {color6.blue}
{color7.red}, {color7.green}, {color7.blue}
{color8.red}, {color8.green}, {color8.blue}
{color9.red}, {color9.green}, {color9.blue}
{color10.red}, {color10.green}, {color10.blue}
{color11.red}, {color11.green}, {color11.blue}
{color12.red}, {color12.green}, {color12.blue}
{color13.red}, {color13.green}, {color13.blue}
{color14.red}, {color14.green}, {color14.blue}
{color15.red}, {color15.green}, {color15.blue}" > "${wal_conf_dir}/templates/colors-decimal"

cosmic_conf_dir="${conf_dir}/cosmic"
cosmic_dark_file="$cosmic_conf_dir/com.system76.CosmicTheme.Mode/v1/is_dark"
cosmic_bg_file="$cosmic_conf_dir/com.system76.CosmicBackground/v1/all"

# customize this function according to your setup. Its pre-
# loaded with my settings, but you'll want to adjust to your
# setup
update () {
	cosmic_set_bg "$theme_dir/$arg/wallpaper"
	cosmic_set_dark_or_light
	cosmic_set_accent
	emacsclient -ue "(progn (load-theme 'ewal-spacemacs-modern)
(modify-all-frames-parameters '((alpha-background . $alpha)))
(adjust-region-faces))" &
	xrdb "$xresources" > /dev/null &
	dwmc xrdb &
	pywalfox update > /dev/null &
	[ -e "$prefix/post-app.sh" ] && sh "$prefix/post-app.sh"
}

component () {
	case "$1" in
		"red"|"r"|1)
			bound1=2
			bound2=3 ;;
		"green"|"g"|2)
			bound1=4
			bound2=5 ;;
		"blue"|"b"|3)
			bound1=6
			bound2=7 ;;
	esac
	hex="$(echo $2 | cut -c ${bound1}-${bound2})"
	printf "%d" "0x${hex}"
}

avg_3 () {
	printf "$(($(($1 + $2 + $3)) / 3))"
}

validate_theme () {
	[ -d "$theme_dir/$arg" ] && return 0
	return 1
}

ensure_theme () {
	if [ -z "$arg" ]; then
		arg="$(ls "$theme_dir" | $dmenu_cmd)"
		[ -z "$arg" ] &&
			echo "No theme chosen." >&2 &&
			return 1
	fi
	validate_theme || (echo "'$arg' is not a valid theme." >&2 &&
			   return 1)
}

get_current_if_ours () {
	test="$(basename "$(grep "wallpaper" \
	                         "$HOME/.cache/wal/colors.json" |
	                    sed 's+/[^/]*/[^/]*$++g')")"
	if [ "$test" = "$(basename "$theme_dir")" ]; then
		arg="$(grep "wallpaper" \
		            "$HOME/.cache/wal/colors.json" |
		       sed 's+/[^/]*$++g')"
		arg="$(basename "$arg")"
		return 0
	else
		echo "Current theme is not managed by newl" >&2
		return 1
	fi
}

ensure_arg_c_possible () {
	failure=""
	if [ "$arg" = "c" ]; then
		get_current_if_ours || failure="y"
	else
		ensure_theme || failure="y"
	fi
	if [ $failure ]; then
		echo "Exiting..."
		exit 1
	fi
}

cosmic_set_bg () {
	if [ "$(echo "$1" | cut -c 1)" != "/" ]; then
		echo "Cosmic needs an absolute path"
		exit 1
	fi

	head="$(head -n 2 "$cosmic_bg_file")"
	tail="$(tail -n 6 "$cosmic_bg_file")"
	echo "$head
    source: Path(\"$(realpath "$1")\"),
$tail" > "$cosmic_bg_file"
}

cosmic_set_dark_or_light () {
	determinant="$(avg_3 "$(component 1 $background)" \
			    "$(component 3 $background)" \
			    "$(component 3 $background)")"
	([ "$determinant" -lt 128 ] \
		 && echo "true" \
		 || echo "false") > "$cosmic_dark_file"
}

cosmic_set_accent () {
	target="$cosmic_conf_dir"/com.system76.CosmicTheme.Dark.Builder/v1/accent
	echo "Some((" > "$target"
	cat "${wal_cache_dir}/colors-decimal" | head -n 5 | tail -n 1 | {
		read -r red blue green
		echo "    red: $red
    green: $green,
    blue: $blue"
	} >> "$target"
	echo "))" >> "$target"
}

command="$1"
arg="$2"

case "$command" in
	"")
		$0 a ;;
	"h"|"-h"|"--help")
		echo "$usage_message" ;;
	"l")
		ls "$theme_dir" ;;
	"l-icewm-menu")
		for theme in $(ls "$theme_dir"); do
			echo "prog \"$theme\" \"$theme_dir/$theme/icon\" newl a \"$theme\""
		done ;;
	"r")
		newl a "$(newl l | shuf -n 1)" ;;
	"s")
		# customise WM_CLASS/instance so our sxiv can be targeted by WMs
		arg="$($sxiv_cmd -N "newl" -bort "$HOME/.local/share/wal-themes"/*/wallpaper)"
		if [ -z "$arg" ]; then
			echo "No theme selected. Exiting..."
			exit 1
		fi
		arg="$(echo "$arg" | sed 's+/wallpaper$++g' | xargs basename)"
	        newl a "$arg" ;;
	"n")
		if [ -z "$2" ]; then
			echo "You must supply a name for the new theme"
			exit 1
		elif validate_theme && [ -z "$3" ]; then
			echo "A theme named '$arg' already exists" \
		             "To update it, use the 'u' command" >&2
			exit 1
		fi
		# extracts filename from JSON
		dest_dir="$theme_dir/$arg"
		wp_orig="$(grep wallpaper "$HOME/.cache/wal/colors.json" |
				      cut -c 19- | sed s/..$//g)"
		colours_orig="$HOME/.cache/wal/colors.json"
		wp_dest="$dest_dir/wallpaper"
		colours_dest="$dest_dir/colours.json"
		mkdir -p "$dest_dir"
		[ "$wp_orig" != "None" ] && cp -f "$wp_orig" "$wp_dest"
		# Fix paths; we could use sed but that'd be unreadable and
		# unnecessarily complex
		head -n 2 "$colours_orig" > "$colours_dest"
		echo "    \"wallpaper\": \"$wp_dest\"," \
		     >> "$colours_dest"
	        tail -n 26 "$colours_orig" >> "$colours_dest"
		magick "$wp_dest" -scale x${icon_size} - |
			magick - -crop $isxis -format png - > "$dest_dir/icon";;
	"a")
		ensure_arg_c_possible
		prefix="$theme_dir/$arg"
		alpha="$(grep "\"alpha\": \"" "$prefix/colours.json" |
		         grep -o -E "[0-9]{2}[0-9]?")"
		wal -f "$prefix/colours.json" > /dev/null
		update ;;
	"i")
		ensure_arg_c_possible
		[ -e "$theme_dir/$arg/info" ] && cat "$theme_dir/$arg/info" ;;
	"e")
		ensure_arg_c_possible
		$EDITOR "$theme_dir/$arg/colours.json" ;;
	"p")
		ensure_arg_c_possible
		if [ -e "$theme_dir/$arg/post-app.sh" ]; then
			$EDITOR "$theme_dir/$arg/post-app.sh"
		else
			printf "#! /usr/bin/env sh\n\n" > \
			       "$theme_dir/$arg/post-app.sh"
			$0 p "$arg"
		fi ;;
	"d")
		if [ -z "$arg" ]; then
			echo "To prevent irreversible deletion of the wrong" \
			     "theme, $name requires explicit specification of" \
			     "target"
			exit 1
		fi
		ensure_arg_c_possible
		rm -r "$theme_dir/$arg" ;;
	"u")
		ensure_arg_c_possible
		$0 n "$arg" "--force" ;;
	"install")
		if [ -z "$2" ]; then
			echo "this command needs an argument"
			exit
		fi
		for arg in "$@"; do
			if ! [ "$arg" = "$1" ]; then
				test -e "${arg}/wallpaper" || \
					echo "Warning: $arg includes no wallpaper"
				test -e "${arg}/colours.json" || \
					echo "Warning: $arg has no colours file"
				mkdir -p "$theme_dir"
				cp -R "$arg" "$theme_dir"
			fi
		done ;;
	*)
		echo "'$command' is not a valid command" >&2 ;;
esac
